language: java
jdk:
  - openjdk11
sudo: false
install: false
dist: bionic
addons:
  sonarqube:
    organization: "anystub1"
    token:
      secure: "duVDfUpV3OtRIsG5htU/PLOBlM/AxWO8gC0RCMStWa99cG028ZiGeQZa83jKmSHssfEjGovDjblYvqvPEOrOrIsfbRggAjzVN74ME5/uVKNekzEdgyzlSEZx9EcO1qlY6+jOUL32Oh2nJ98Oq2nzyz+SbsgUHL/2Da9HiDiUznIyRvId/Clpm0nF3hBb5Ixibdw6kJFmQ7BNmrMKHBmfI6qoBt5GdB5UEtNS3Rec0cscmLsUAMdeff1HzGsE4/0vh7nV5/BBB/r3rJGXVUgyJuZy6u0jdjjd+MtsvipXAoXZWcjB4a3/mM97gaBFjGbrXBZ/jyTBwZ8H419hTKwCiRMK9x69KQvYWzjBvEV3SJbUnwkcaq+C54sy1myy2jD6OwBb4EkRCX5jb7Z97M/c0PKXYMG9gQ+cStu5yN+dfdjWILGc/zlFRQ+U1MIzJi0RH/DBOD2taBNJA14ceB9Kz3lscg4wMfDkZKoPeSyNajlqh4HXjRFP04GDj4GJbd8eJT4qWLMLdkkA5PVWgVeGWw4WeV2ANYaF0dNsJy0h40aBcoKYovlmU4IlSZUVD40Eo1XlmLouG8o21Cr3JeOy5AbQ3i9o6/bgvkrquo4p086hPU8vXZ1SvI6KF/oLjLVf7jzeOuDUHCGoUvEjvcpAM0r3lKNKQ0G9f9+d0gmAQtQ="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar